
let radialKeyCards = [
    new keyCard("KeyA", "A"),
    new keyCard("KeyB", "B"),
    new keyCard("KeyC", "C"),
    new keyCard("KeyD", "D"),
    new keyCard("KeyE", "E"),
    new keyCard("KeyF", "F"),
    new keyCard("KeyG", "G"),
    new keyCard("KeyH", "H"),
    new keyCard("KeyI", "I"),
    new keyCard("KeyJ", "J"),
    new keyCard("KeyK", "K"),
    new keyCard("KeyL", "L"),
    new keyCard("KeyM", "M"),
    new keyCard("KeyN", "N"),
    new keyCard("KeyO", "O"),
    new keyCard("KeyP", "P"),
    new keyCard("KeyQ", "Q"),
    new keyCard("KeyR", "R"),
    new keyCard("KeyS", "S"),
    new keyCard("KeyT", "T"),
    new keyCard("KeyU", "U"),
    new keyCard("KeyV", "V"),
    new keyCard("KeyW", "W"),
    new keyCard("KeyX", "X"),
    new keyCard("KeyY", "Y"),
    new keyCard("KeyZ", "Z"),
]